import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TodoList Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} container bg-slate-900 text-slate-200 mx-auto p-4 min-w-80 min-h-screen flex flex-col items-center justify-between`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
